/**
 * Pillai College of Engineering - Alegria Festival Seed Dataset
 * Dr. K. M. Vasudevan Pillai Campus, Sector 16, New Panvel, Navi Mumbai (~ 18.9902, 73.1277)
 * Realistic campus layout grounded in student ground-truth:
 * - Gate 1 (Main Gate, Sector 16 Road): Girls entry, Artists & VIPs, Ticket/ID Turnstiles
 * - Gate 2 (Canteen Back Gate): Boys entry & Canteen food stalls
 * - Gate 3 (Back Gymkhana / Service Gate): Standby / Emergency Egress Corridor
 * - Main Festival Ground / Sports Ground: 10k Capacity Concert Stage & Celebrity EDM Night
 * - The Quadrangle (The Quad): Central student hub, flashmobs & daytime band battles
 * - Transit feeder: Panvel Railway Station & Sector 16 Auto/Bus Depot
 */

const baseDate = new Date();
baseDate.setMinutes(0, 0, 0);

const mockZones = [
  {
    _id: 'zone-main-ground',
    name: 'Alegria Main Concert Ground',
    category: 'venue_cluster',
    geoCenter: { lat: 18.9908, lng: 73.1282 },
    geoBoundary: {
      type: 'Polygon',
      coordinates: [
        [18.9915, 73.1278],
        [18.9916, 73.1288],
        [18.9903, 73.1289],
        [18.9902, 73.1279],
      ],
    },
    totalCapacity: { venue: 7000, transit: 4000, hospitality: 1500 },
    liveMetrics: {
      currentVenueOccupancy: 5850,
      currentTransitPressure: 0.92,
      currentHospitalityOccupancy: 1200,
      compositeStressScore: 88,
      status: 'critical',
      lastUpdated: new Date(),
    },
    metadata: {
      accessibilityScore: 92,
      transitConnectedZoneIds: ['zone-quadrangle', 'zone-sports-ground'],
      notes: 'Celebrity Headliner & DJ EDM Night arena. Major egress choke post 22:30.',
    },
  },
  {
    _id: 'zone-quadrangle',
    name: 'The Central Quadrangle (The Quad)',
    category: 'venue_cluster',
    geoCenter: { lat: 18.9902, lng: 73.1277 },
    geoBoundary: {
      type: 'Polygon',
      coordinates: [
        [18.9906, 73.1274],
        [18.9907, 73.1280],
        [18.9898, 73.1281],
        [18.9897, 73.1275],
      ],
    },
    totalCapacity: { venue: 2500, transit: 3500, hospitality: 1200 },
    liveMetrics: {
      currentVenueOccupancy: 1850,
      currentTransitPressure: 0.68,
      currentHospitalityOccupancy: 850,
      compositeStressScore: 66,
      status: 'elevated',
      lastUpdated: new Date(),
    },
    metadata: {
      accessibilityScore: 98,
      transitConnectedZoneIds: ['zone-main-ground', 'zone-canteen-back', 'zone-atrium-main'],
      notes: 'Central student crossing hub. Alegria Flashmobs and daytime Band Battles.',
    },
  },
  {
    _id: 'zone-canteen-back',
    name: 'Campus Canteen & Boys Gate 2',
    category: 'hospitality',
    geoCenter: { lat: 18.9895, lng: 73.1272 },
    geoBoundary: {
      type: 'Polygon',
      coordinates: [
        [18.9899, 73.1268],
        [18.9900, 73.1275],
        [18.9890, 73.1276],
        [18.9889, 73.1269],
      ],
    },
    totalCapacity: { venue: 1800, transit: 2500, hospitality: 2000 },
    liveMetrics: {
      currentVenueOccupancy: 1100,
      currentTransitPressure: 0.48,
      currentHospitalityOccupancy: 1400,
      compositeStressScore: 46,
      status: 'normal',
      lastUpdated: new Date(),
    },
    metadata: {
      accessibilityScore: 95,
      transitConnectedZoneIds: ['zone-quadrangle', 'zone-panvel-transit', 'zone-sports-ground'],
      notes: 'Dedicated Boys Entry Gate 2 and cafeteria food stalls.',
    },
  },
  {
    _id: 'zone-atrium-main',
    name: 'Engineering Atrium & Girls/Artist Gate 1',
    category: 'venue_cluster',
    geoCenter: { lat: 18.9900, lng: 73.1280 },
    geoBoundary: {
      type: 'Polygon',
      coordinates: [
        [18.9904, 73.1278],
        [18.9905, 73.1285],
        [18.9895, 73.1286],
        [18.9894, 73.1279],
      ],
    },
    totalCapacity: { venue: 2000, transit: 3500, hospitality: 800 },
    liveMetrics: {
      currentVenueOccupancy: 1350,
      currentTransitPressure: 0.54,
      currentHospitalityOccupancy: 450,
      compositeStressScore: 52,
      status: 'normal',
      lastUpdated: new Date(),
    },
    metadata: {
      accessibilityScore: 100,
      transitConnectedZoneIds: ['zone-quadrangle', 'zone-panvel-transit', 'zone-sports-ground', 'zone-canteen-back'],
      notes: 'Main Sector 16 Entrance (Gate 1). Dedicated Girls & Artist access, ID & ticket scanning turnstiles.',
    },
  },
  {
    _id: 'zone-sports-ground',
    name: 'PICA Lawn & Sports Ground',
    category: 'buffer',
    geoCenter: { lat: 18.9912, lng: 73.1270 },
    geoBoundary: {
      type: 'Polygon',
      coordinates: [
        [18.9918, 73.1265],
        [18.9919, 73.1274],
        [18.9907, 73.1275],
        [18.9906, 73.1266],
      ],
    },
    totalCapacity: { venue: 2000, transit: 1500, hospitality: 1500 },
    liveMetrics: {
      currentVenueOccupancy: 550,
      currentTransitPressure: 0.22,
      currentHospitalityOccupancy: 400,
      compositeStressScore: 24,
      status: 'normal',
      lastUpdated: new Date(),
    },
    metadata: {
      accessibilityScore: 95,
      transitConnectedZoneIds: ['zone-main-ground', 'zone-canteen-back', 'zone-atrium-main'],
      notes: 'Open green lawns, PICA Architecture ramp, acoustic sets, and low-density detour corridor.',
    },
  },
  {
    _id: 'zone-panvel-transit',
    name: 'Panvel Station & Sector 16 Transit Hub',
    category: 'transit_hub',
    geoCenter: { lat: 18.9915, lng: 73.1220 },
    geoBoundary: {
      type: 'Polygon',
      coordinates: [
        [18.9930, 73.1205],
        [18.9935, 73.1235],
        [18.9900, 73.1240],
        [18.9895, 73.1210],
      ],
    },
    totalCapacity: { venue: 3000, transit: 10000, hospitality: 3000 },
    liveMetrics: {
      currentVenueOccupancy: 2200,
      currentTransitPressure: 0.65,
      currentHospitalityOccupancy: 1700,
      compositeStressScore: 58,
      status: 'normal',
      lastUpdated: new Date(),
    },
    metadata: {
      accessibilityScore: 96,
      transitConnectedZoneIds: ['zone-atrium-main', 'zone-canteen-back'],
      notes: 'Panvel Railway Station feeder, NMMT bus stop, and Sector 16 Auto-rickshaw depot.',
    },
  },
];

const mockVenues = [
  {
    _id: 'venue-alegria-main-stage',
    name: 'Alegria Main Concert Arena (Sports Ground)',
    zoneId: 'zone-main-ground',
    category: 'stadium',
    location: { lat: 18.9908, lng: 73.1282 },
    maxCapacity: 7000,
    currentOccupancy: 5850,
    ingressRatePerMin: 180,
    egressRatePerMin: 320,
    scheduledEvents: [
      {
        eventId: 'evt-alegria-edm-night',
        name: 'Celebrity Headliner & DJ EDM Night',
        startTime: new Date(baseDate.getTime() + 45 * 60 * 1000),
        endTime: new Date(baseDate.getTime() + 180 * 60 * 1000),
        ticketedAttendance: 6800,
        status: 'upcoming',
      },
    ],
  },
  {
    _id: 'venue-quad-stage',
    name: 'The Quadrangle Cultural Stage',
    zoneId: 'zone-quadrangle',
    category: 'stadium',
    location: { lat: 18.9902, lng: 73.1277 },
    maxCapacity: 2500,
    currentOccupancy: 1850,
    ingressRatePerMin: 120,
    egressRatePerMin: 140,
    scheduledEvents: [
      {
        eventId: 'evt-alegria-flashmob',
        name: 'Alegria Mega Flashmob & Battle of the Bands',
        startTime: new Date(baseDate.getTime() + 15 * 60 * 1000),
        endTime: new Date(baseDate.getTime() + 105 * 60 * 1000),
        ticketedAttendance: 2300,
        status: 'upcoming',
      },
    ],
  },
  {
    _id: 'venue-atrium-hall',
    name: 'Engineering Concourse & Atrium Arena',
    zoneId: 'zone-atrium-main',
    category: 'fan_park',
    location: { lat: 18.9900, lng: 73.1280 },
    maxCapacity: 2000,
    currentOccupancy: 1350,
    ingressRatePerMin: 90,
    egressRatePerMin: 110,
    scheduledEvents: [
      {
        eventId: 'evt-alegria-fashion',
        name: 'Mr. & Ms. Alegria Fashion Night & Tech Showcase',
        startTime: new Date(baseDate.getTime() + 60 * 60 * 1000),
        endTime: new Date(baseDate.getTime() + 150 * 60 * 1000),
        ticketedAttendance: 1700,
        status: 'upcoming',
      },
    ],
  },
];

const mockTransitEdges = [
  {
    _id: 'edge-depot-maingate',
    name: 'Sector 16 Auto Loop ⇄ Main Gate 1 (Girls & Artist Entry)',
    fromZoneId: 'zone-panvel-transit',
    toZoneId: 'zone-atrium-main',
    mode: 'shuttle_bus',
    distanceMeters: 600,
    baseTravelTimeMinutes: 3,
    maxThroughputPerHour: 4000,
    pathCoordinates: [
      [18.9915, 73.1220],
      [18.9908, 73.1250],
      [18.9900, 73.1280],
    ],
    liveStatus: {
      currentFlowPerHour: 2600,
      currentTravelTimeMinutes: 4,
      utilizationRate: 0.65,
      congestionLevel: 'moderate',
      isActive: true,
      shuttlesAssigned: 8,
    },
  },
  {
    _id: 'edge-depot-canteengate',
    name: 'Sector 16 Walkway ⇄ Canteen Back Gate 2 (Boys Entry)',
    fromZoneId: 'zone-panvel-transit',
    toZoneId: 'zone-canteen-back',
    mode: 'pedestrian_walkway',
    distanceMeters: 550,
    baseTravelTimeMinutes: 4,
    maxThroughputPerHour: 3500,
    pathCoordinates: [
      [18.9915, 73.1220],
      [18.9905, 73.1245],
      [18.9895, 73.1272],
    ],
    liveStatus: {
      currentFlowPerHour: 1800,
      currentTravelTimeMinutes: 4,
      utilizationRate: 0.51,
      congestionLevel: 'moderate',
      isActive: true,
      shuttlesAssigned: 0,
    },
  },
  {
    _id: 'edge-maingate-quad',
    name: 'Main Gate Concourse ⇄ The Quad',
    fromZoneId: 'zone-atrium-main',
    toZoneId: 'zone-quadrangle',
    mode: 'pedestrian_walkway',
    distanceMeters: 140,
    baseTravelTimeMinutes: 2,
    maxThroughputPerHour: 5000,
    pathCoordinates: [
      [18.9900, 73.1280],
      [18.9901, 73.1278],
      [18.9902, 73.1277],
    ],
    liveStatus: {
      currentFlowPerHour: 3100,
      currentTravelTimeMinutes: 2,
      utilizationRate: 0.62,
      congestionLevel: 'moderate',
      isActive: true,
      shuttlesAssigned: 0,
    },
  },
  {
    _id: 'edge-canteengate-quad',
    name: 'Canteen Gate 2 ⇄ The Quad Concourse',
    fromZoneId: 'zone-canteen-back',
    toZoneId: 'zone-quadrangle',
    mode: 'pedestrian_walkway',
    distanceMeters: 160,
    baseTravelTimeMinutes: 2,
    maxThroughputPerHour: 4500,
    pathCoordinates: [
      [18.9895, 73.1272],
      [18.9899, 73.1274],
      [18.9902, 73.1277],
    ],
    liveStatus: {
      currentFlowPerHour: 2200,
      currentTravelTimeMinutes: 2,
      utilizationRate: 0.49,
      congestionLevel: 'moderate',
      isActive: true,
      shuttlesAssigned: 0,
    },
  },
  {
    _id: 'edge-quad-mainground',
    name: 'The Quad ⇄ Main Concert Ground (Arena Concourse)',
    fromZoneId: 'zone-quadrangle',
    toZoneId: 'zone-main-ground',
    mode: 'pedestrian_walkway',
    distanceMeters: 180,
    baseTravelTimeMinutes: 3,
    maxThroughputPerHour: 5500,
    pathCoordinates: [
      [18.9902, 73.1277],
      [18.9905, 73.1280],
      [18.9908, 73.1282],
    ],
    liveStatus: {
      currentFlowPerHour: 5100,
      currentTravelTimeMinutes: 7,
      utilizationRate: 0.92,
      congestionLevel: 'gridlock',
      isActive: true,
      shuttlesAssigned: 0,
    },
  },
  {
    _id: 'edge-canteen-sports',
    name: 'Canteen Food Street ⇄ PICA Lawn & Sports Ground (Crowd-Free Bypass)',
    fromZoneId: 'zone-canteen-back',
    toZoneId: 'zone-sports-ground',
    mode: 'pedestrian_walkway',
    distanceMeters: 280,
    baseTravelTimeMinutes: 4,
    maxThroughputPerHour: 4000,
    pathCoordinates: [
      [18.9895, 73.1272],
      [18.9904, 73.1269],
      [18.9912, 73.1270],
    ],
    liveStatus: {
      currentFlowPerHour: 1100,
      currentTravelTimeMinutes: 4,
      utilizationRate: 0.28,
      congestionLevel: 'free_flow',
      isActive: true,
      shuttlesAssigned: 0,
    },
  },
  {
    _id: 'edge-emergency-gate3',
    name: 'Main Stage Backstage ⇄ Gate 3 (Emergency Ambulance / Service Corridor)',
    fromZoneId: 'zone-main-ground',
    toZoneId: 'zone-sports-ground',
    mode: 'shuttle_bus',
    distanceMeters: 220,
    baseTravelTimeMinutes: 2,
    maxThroughputPerHour: 2000,
    pathCoordinates: [
      [18.9908, 73.1282],
      [18.9910, 73.1275],
      [18.9912, 73.1270],
    ],
    liveStatus: {
      currentFlowPerHour: 400,
      currentTravelTimeMinutes: 2,
      utilizationRate: 0.20,
      congestionLevel: 'free_flow',
      isActive: true,
      shuttlesAssigned: 4,
    },
  },
  {
    _id: 'edge-sports-mainground',
    name: 'PICA Lawn ⇄ Main Concert Ground (North Perimeter Bypass)',
    fromZoneId: 'zone-sports-ground',
    toZoneId: 'zone-main-ground',
    mode: 'pedestrian_walkway',
    distanceMeters: 190,
    baseTravelTimeMinutes: 2,
    maxThroughputPerHour: 4000,
    pathCoordinates: [
      [18.9912, 73.1270],
      [18.9914, 73.1276],
      [18.9908, 73.1282],
    ],
    liveStatus: {
      currentFlowPerHour: 800,
      currentTravelTimeMinutes: 2,
      utilizationRate: 0.22,
      congestionLevel: 'free_flow',
      isActive: true,
      shuttlesAssigned: 0,
    },
  },
  {
    _id: 'edge-maingate-canteen',
    name: 'Gate 1 Concourse ⇄ Campus Canteen Internal Arcade',
    fromZoneId: 'zone-atrium-main',
    toZoneId: 'zone-canteen-back',
    mode: 'pedestrian_walkway',
    distanceMeters: 180,
    baseTravelTimeMinutes: 2,
    maxThroughputPerHour: 3500,
    pathCoordinates: [
      [18.9900, 73.1280],
      [18.9897, 73.1276],
      [18.9895, 73.1272],
    ],
    liveStatus: {
      currentFlowPerHour: 1200,
      currentTravelTimeMinutes: 2,
      utilizationRate: 0.34,
      congestionLevel: 'free_flow',
      isActive: true,
      shuttlesAssigned: 0,
    },
  },
  {
    _id: 'edge-atrium-sports',
    name: 'Engineering Atrium ⇄ PICA Architecture Ramp (Step-Free Bypass)',
    fromZoneId: 'zone-atrium-main',
    toZoneId: 'zone-sports-ground',
    mode: 'pedestrian_walkway',
    distanceMeters: 210,
    baseTravelTimeMinutes: 3,
    maxThroughputPerHour: 4500,
    pathCoordinates: [
      [18.9900, 73.1280],
      [18.9906, 73.1275],
      [18.9912, 73.1270],
    ],
    liveStatus: {
      currentFlowPerHour: 950,
      currentTravelTimeMinutes: 3,
      utilizationRate: 0.24,
      congestionLevel: 'free_flow',
      isActive: true,
      shuttlesAssigned: 0,
    },
  },
];

const mockConcessions = [
  {
    _id: 'conc-canteen-main',
    name: 'Campus Canteen & Food Plaza',
    category: 'food',
    zoneId: 'zone-canteen-back',
    locationDescription: 'Ground floor cafeteria lane near Boys Gate 2',
    distanceMetersFromZone: 20,
    baseWaitMinutes: 3,
    capacityRating: 'normal',
    isOpen: true,
    features: ['Nescafe Coffee Booth', 'Frankie Stall', 'Dosa & Sandwich Counter', 'Cold Juices', 'UPI Enabled'],
    statusNote: 'Frankie, Dosa & Juices counters open • Rapid UPI queue',
  },
  {
    _id: 'conc-arena-food',
    name: 'Concert Arena Food Kiosks',
    category: 'food',
    zoneId: 'zone-main-ground',
    locationDescription: 'North-East perimeter of Alegria Main Stage',
    distanceMetersFromZone: 30,
    baseWaitMinutes: 18,
    capacityRating: 'high',
    isOpen: true,
    features: ['Popcorn & Nachos', 'Energy Drinks', 'Bottled Mineral Water', 'Fast Food'],
    statusNote: 'High queue density (18 min wait)',
  },
  {
    _id: 'conc-atrium-cafe',
    name: 'Engineering Atrium Quick Bites',
    category: 'food',
    zoneId: 'zone-atrium-main',
    locationDescription: 'Main lobby near Girls/VIP Gate 1 turnstiles',
    distanceMetersFromZone: 15,
    baseWaitMinutes: 2,
    capacityRating: 'low',
    isOpen: true,
    features: ['Chilled Coffee', 'Packaged Snacks', 'Water Bottles'],
    statusNote: 'Zero queue • Instant counter service',
  },
  {
    _id: 'conc-pica-lawn',
    name: 'PICA Architecture Lawn & Chill Courtyard',
    category: 'relax',
    zoneId: 'zone-sports-ground',
    locationDescription: 'Open architecture wing garden with shaded tree benches',
    distanceMetersFromZone: 25,
    baseWaitMinutes: 0,
    capacityRating: 'low',
    isOpen: true,
    features: ['Shaded Green Lawns', 'Phone Charging Kiosks', 'Free Chilled Water Dispenser', 'Acoustic Sound Level'],
    statusNote: 'Calm retreat away from concert bass • 25% capacity',
  },
  {
    _id: 'conc-atrium-foyer',
    name: 'Engineering Concourse Acoustic Foyer',
    category: 'relax',
    zoneId: 'zone-atrium-main',
    locationDescription: '1st floor atrium gallery overlooking main entrance',
    distanceMetersFromZone: 40,
    baseWaitMinutes: 0,
    capacityRating: 'low',
    isOpen: true,
    features: ['Air-Conditioned Indoor Hall', 'Seating Couches', 'WiFi Hotspot'],
    statusNote: 'Quiet indoor resting space',
  },
  {
    _id: 'conc-quad-screen',
    name: 'The Quad Mega 4K Concert Screen',
    category: 'screens',
    zoneId: 'zone-quadrangle',
    locationDescription: 'Suspended above the central quadrangle amphitheater',
    distanceMetersFromZone: 10,
    baseWaitMinutes: 0,
    capacityRating: 'high',
    isOpen: true,
    features: ['Ultra-HD 4K Screen', 'Simulcast of Main EDM Stage', 'Surround Audio'],
    statusNote: 'Live concert broadcast running • Crowded viewing area',
  },
  {
    _id: 'conc-turf-screen',
    name: 'Sports Turf 4K LED Screen & Fan Park',
    category: 'screens',
    zoneId: 'zone-sports-ground',
    locationDescription: 'Basketball court perimeter display',
    distanceMetersFromZone: 35,
    baseWaitMinutes: 0,
    capacityRating: 'low',
    isOpen: true,
    features: ['Open Air 4K Screen', 'Spacious Seating', 'Live Replays'],
    statusNote: 'Uncrowded open-air viewing with clear sightlines',
  },
  {
    _id: 'conc-engg-restroom',
    name: 'Ground Floor Engineering Restroom Suite',
    category: 'restrooms',
    zoneId: 'zone-atrium-main',
    locationDescription: 'Behind main elevators near Gate 1 entrance',
    distanceMetersFromZone: 30,
    baseWaitMinutes: 1,
    capacityRating: 'low',
    isOpen: true,
    features: ['10 Clean Stalls', 'Wheelchair Accessible', 'Sanitized Frequently', 'Running Water & Handwash'],
    statusNote: '0 min wait • Sanitized 5 mins ago',
  },
  {
    _id: 'conc-canteen-restroom',
    name: 'Canteen Cafeteria Washrooms',
    category: 'restrooms',
    zoneId: 'zone-canteen-back',
    locationDescription: 'Adjacent to canteen seating arcade near Gate 2',
    distanceMetersFromZone: 45,
    baseWaitMinutes: 3,
    capacityRating: 'normal',
    isOpen: true,
    features: ['Separate Gents & Ladies Wings', 'Mirrors & Wash Basins'],
    statusNote: '2 - 3 min queue',
  },
  {
    _id: 'conc-arena-porta',
    name: 'Concert Arena Mobile Sanitation Cluster',
    category: 'restrooms',
    zoneId: 'zone-main-ground',
    locationDescription: 'South concourse perimeter of the sports ground',
    distanceMetersFromZone: 60,
    baseWaitMinutes: 12,
    capacityRating: 'high',
    isOpen: true,
    features: ['16 Mobile Restroom Cabins', 'Attendant on Duty'],
    statusNote: 'Heavy usage post-performance (10-12 min queue)',
  },
  {
    _id: 'conc-sector16-auto',
    name: 'Sector 16 Auto Rickshaw Bay & Share-Auto Loop',
    category: 'transit',
    zoneId: 'zone-panvel-transit',
    locationDescription: 'Sector 16 junction outside campus gates',
    distanceMetersFromZone: 50,
    baseWaitMinutes: 3,
    capacityRating: 'normal',
    isOpen: true,
    features: ['Direct Share-Auto to Panvel Station (₹25-30)', 'Vehicles Departing Every 2 Mins', 'Pre-paid Auto Helpdesk'],
    statusNote: 'Continuous departures to Panvel Railway Station',
  },
  {
    _id: 'conc-nmmt-bus',
    name: 'Panvel Station NMMT Feeder Bus Depot',
    category: 'transit',
    zoneId: 'zone-panvel-transit',
    locationDescription: 'Sector 16 depot bus bay',
    distanceMetersFromZone: 70,
    baseWaitMinutes: 8,
    capacityRating: 'normal',
    isOpen: true,
    features: ['NMMT Route 24 & 50', 'Direct to Panvel Station & Navi Mumbai Belapur'],
    statusNote: 'Next feeder bus in 7 mins',
  },
];

const mockAnnouncements = [
  {
    _id: 'ann-alegria-headliner',
    title: 'Celebrity Headliner & DJ EDM Night Commencing',
    message: 'EDM Mainstage performances are starting in the Main Concert Ground. North-West lawn entrance via PICA ramp is open with zero queue.',
    severity: 'info',
    targetZoneId: 'zone-main-ground',
    author: 'Alegria Core Operations',
    isPinned: false,
    isActive: false,
    createdAt: new Date(),
  },
  {
    _id: 'ann-quad-bottleneck',
    title: 'High Crowd Density Warning: The Quadrangle',
    message: 'The Quad is at 92% capacity during the Battle of the Bands. Please bypass via the PICA Architecture ADA ramp to avoid concourse crush.',
    severity: 'warning',
    targetZoneId: 'zone-quadrangle',
    author: 'Campus Safety & Crowd Triage',
    isPinned: false,
    isActive: true,
    createdAt: new Date(),
  },
  {
    _id: 'ann-gate-guidance',
    title: 'Gate Entry Access Rules in Effect',
    message: 'Gate 1 (Sector 16) is dedicated to Girls, VIPs & Artists with Pillai ID scanners. Boys must proceed to Gate 2 (Canteen Back Gate) for security frisking.',
    severity: 'info',
    targetZoneId: null,
    author: 'Pillai Campus Security',
    isPinned: false,
    isActive: true,
    createdAt: new Date(),
  },
];

module.exports = {
  mockZones,
  mockVenues,
  mockTransitEdges,
  mockConcessions,
  mockAnnouncements,
};

